Update CLJ/CLJS/JS libraries, client code cleanup
* Upgrade library versions
  * Upgrade shadow-cljs to 2.10.21
  * Upgrade chart.js to 2.9.3, update code for changes
    * Update location of :maxBarThickness option
  * Upgrade react-dnd, small code change to match new version
  * Upgrade semantic-ui-react, react-stripe-elements (no code changes)
  * Upgrade re-frame to 1.0.0 (no code changes)
  * Upgrade other libraries (js, cljs, clj)
* Wrap with-project-cache on concordance API call
* Code style changes
  * Rename `util/string-ellipsis` to `util/ellipsis-middle`
  * Add `util/ellipsize` (trailing string ellipsis)
  * Change function names to follow convention of CamelCase names for
    reagent components.
  * Change many defn to defn- in cljs code
  * Change some reg-sub forms to use `:<-` syntax where possible
* Fix clj-kondo warnings
  * Remove many unused references in (ns (:require ...))
  * Fix some misplaced function docstrings
* HTML changes
  * Change block-display <span> elements to <div> elements
  * Remove <br> elements, use <p> elements instead
  * Fix elements having "aligned" class without matching
    "center"/"left"/"right"/"middle".
  * Use <a href="#" ...> instead of {:style {:cursor "pointer"}}
* Change code in analytics/concordance.cljs and analytics/labels.cljs
  for formatting and code size.
  * Avoid lines exceeding 100 columns
  * Comment out unused functions
  * Replace some `reduce` calls using map/filter/etc.
  * Add generic `StepTitle` component
  * Simplify arguments to set-subscription-button

Upgrade chartjs, more client code cleanup [squashed]

* Upgrade shadow-cljs to 2.11.0 (no code changes)
* Upgrade chartjs to 3.0.0-alpha.2, update code for new API
* Add watch on resources/public/css to shadow-cljs dev profile
* Change code in ./chromedriver script
* Add ./scripts/build-cljs (doesn't force complete rebuild)
* Refactor for shorter code in project/analytics.cljs
* Minor cleanup in analytics/feedback.cljs
  * Increase iframe size (avoid internal scrollbars)
* Minor cleanup in project/compensation.cljs
  * Change defn to defn-, comment out unused function

diff --git a/scripts/init-clj-kondo b/scripts/init-clj-kondo
--- a/scripts/init-clj-kondo
+++ b/scripts/init-clj-kondo
@@ -3,29 +3,25 @@
 set -eu
 
 clj-kondo --version > /dev/null || (
-    echo "error: clj-kondo not installed"
-    echo
-    echo "Source:"
-    echo "https://github.com/borkdude/clj-kondo"
-    echo
-    echo "Using npm:"
-    echo "npm install -g clj-kondo"
-    echo
-    exit 1
+  echo "error: clj-kondo not installed"
+  echo
+  echo "Source:"
+  echo "https://github.com/borkdude/clj-kondo"
+  echo
+  echo "Using npm:"
+  echo "npm install -g clj-kondo"
+  echo
+  exit 1
 )
 
 which shadow-cljs > /dev/null || (
-    echo "error: shadow-cljs not installed"
-    echo
-    echo "Using npm:"
-    echo "npm install -g shadow-cljs"
-    echo
-    exit 1
+  echo "error: shadow-cljs not installed"
+  echo
+  echo "Using npm:"
+  echo "npm install -g shadow-cljs"
+  echo
+  exit 1
 )
-
-echo
-echo "initializing clj-kondo cache"
-echo
 
 cpath_server=$(lein with-profile +test classpath)
 cd client
@@ -33,12 +29,11 @@ cpath_client=$(shadow-cljs classpath)
 cd ..
 
 clj_kondo_quiet() {
-    classpath="$@"
-    clj-kondo --lint $classpath | grep -v 'warning:' | grep -v 'error:' || true
+  classpath="$@"
+  clj-kondo --lint $classpath | grep -v 'warning:' | grep -v 'error:' || true
 }
 
 echo "processing CLJ project ..."
 clj_kondo_quiet $cpath_server
 echo "processing CLJS project ..."
 cd client ; clj_kondo_quiet $cpath_client ; cd ..
-echo "finished"
