Add fail with error message in run-dev-containers

diff --git a/scripts/run-dev-containers b/scripts/run-dev-containers
--- a/scripts/run-dev-containers
+++ b/scripts/run-dev-containers
@@ -6,8 +6,9 @@ cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
 
 if command -v podman-compose >/dev/null 2>&1; then
   podman-compose -f ../docker-compose-dev.yml up -d
+elif command -v docker-compose >/dev/null 2>&1; then
+  sudo docker-compose -f ../docker-compose-dev.yml up -d
 else
-  if command -v docker-compose >/dev/null 2>&1; then
-    sudo docker-compose -f ../docker-compose-dev.yml up -d
-  fi
+  echo "[$0] ERROR: couldn't find podman-compose or docker-compose" >&2
+  false
 fi
